version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:8000"
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - /app/venv
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
